# Generated by Django 5.1.6 on 2025-03-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletmanager',
            name='upload_file',
        ),
    ]
