# Generated by Django 5.1.6 on 2025-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletInfoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='outlet_info/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='receivable_value',
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='file',
            field=models.FileField(default=1, upload_to='sales_reports/'),
            preserve_default=False,
        ),
    ]
