# Generated by Django 5.1.6 on 2025-03-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_outletinfoupload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutletInfoUpload',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='file',
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='invoice_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='item_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='receivable_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
