# Generated by Django 5.1.6 on 2025-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_remove_outletmanager_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='daily_sales_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
