# Generated by Django 5.1.6 on 2025-03-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_customer_discountgift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountgift',
            name='customer',
        ),
        migrations.CreateModel(
            name='RedeemedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaign.customer')),
                ('discount_gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.discountgift')),
            ],
        ),
    ]
