# Generated by Django 5.1.6 on 2025-03-06 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_remove_discountgift_customer_redeemeddiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='discountgift',
            name='discount_text',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.customer')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.discountgift')),
            ],
        ),
        migrations.DeleteModel(
            name='RedeemedDiscount',
        ),
    ]
