# Generated by Django 5.1.6 on 2025-03-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_dailysalesreport_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalesreport',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
